services:
  db:
    image: postgres:16.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db
  web:
    build: ./app
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - cache # new
  cache: # new
    image: redis:7.2.4
    restart: always
    ports:
      - 6379:6379
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
volumes:
  postgres_data:
